### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by Zoardedz** [polybiusproxy/Endor#2]

**Comment by polybiusproxy** [comment]
Hello!

Yes, you can compile this as any normal Haxe project!
The only dependency you need is the Format library (https://github.com/HaxeFoundation/format), and you'll be good to go!

Note that Endor only supports Windows at the moment, so it's currently not possible to compile Linux or macOS binaries.

Cheers,
Daniel.

**Comment by Zoardedz** [comment]
yes, but when i tried to yknow just haxe build.hxml it threw up and gave me this: ![image](https://user-images.githubusercontent.com/92955177/194668951-e6199617-2a6f-42ee-b0ba-3b15f51a566a.png)

**Comment by Zoardedz** [comment]
i tried for example to go to the glad source code and search for a glad.xml but couldn't find it

**Comment by polybiusproxy** [comment]
> yes, but when i tried to yknow just haxe build.hxml it threw up and gave me this: ![image](https://user-images.githubusercontent.com/92955177/194668951-e6199617-2a6f-42ee-b0ba-3b15f51a566a.png)

Oh, yes, I forgot!

I didn't use relative paths, so you must change them in GLAD.hx, AL.hx, ALC.hx and GLFW.hx

Cheers,
Daniel.
